apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008  # You can set this manually or leave it to Kubernetes
  selector:
    app: wordpress
